"""Fix media and user multiple relations

Revision ID: 1738087a8973
Revises: 6bd9aaee6651
Create Date: 2021-02-28 22:26:21.229682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1738087a8973'
down_revision = '6bd9aaee6651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_media_created_by'), 'media', ['created_by'], unique=False)
    op.create_foreign_key('fk_media_created_by', 'media', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_media_created_by', 'media', type_='foreignkey')
    op.drop_index(op.f('ix_media_created_by'), table_name='media')
    op.drop_column('media', 'created_by')
    # ### end Alembic commands ###
