"""refactor media model and relationships

Revision ID: 24853bd71dd8
Revises: 143ea375d5af
Create Date: 2021-02-27 00:03:59.247248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24853bd71dd8'
down_revision = '143ea375d5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('begin_date', sa.DateTime(), nullable=True))
    op.add_column('media', sa.Column('duration', sa.Time(), nullable=True))
    op.add_column('media', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_media_site_id'), 'media', ['site_id'], unique=False)
    op.create_foreign_key('fk_media_site', 'media', 'site', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_media_site', 'media', type_='foreignkey')
    op.drop_index(op.f('ix_media_site_id'), table_name='media')
    op.drop_column('media', 'site_id')
    op.drop_column('media', 'duration')
    op.drop_column('media', 'begin_date')
    # ### end Alembic commands ###
