"""Device_model becomes model_name

Revision ID: 3db3fb6ebadb
Revises: 3f45586f3bd5
Create Date: 2021-03-08 20:44:24.547722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3db3fb6ebadb'
down_revision = '3f45586f3bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('model_name', sa.String(), nullable=True))
    op.drop_index('ix_device_device_model', table_name='device')
    op.create_index(op.f('ix_device_model_name'), 'device', ['model_name'], unique=True)
    op.drop_column('device', 'device_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_device_model_name'), table_name='device')
    op.create_index('ix_device_device_model', 'device', ['device_model'], unique=True)
    op.drop_column('device', 'model_name')
    # ### end Alembic commands ###
