"""SITE is_private column and unique device_model in DEVICE

Revision ID: 3f45586f3bd5
Revises: 1738087a8973
Create Date: 2021-03-01 08:15:39.921147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f45586f3bd5'
down_revision = '1738087a8973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_device_model', table_name='device')
    op.create_index(op.f('ix_device_device_model'), 'device', ['device_model'], unique=True)
    op.add_column('site', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.drop_index('ix_site_public_private', table_name='site')
    op.drop_column('site', 'public_private')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('public_private', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_site_public_private', 'site', ['public_private'], unique=False)
    op.drop_column('site', 'is_private')
    op.drop_index(op.f('ix_device_device_model'), table_name='device')
    op.create_index('ix_device_device_model', 'device', ['device_model'], unique=False)
    # ### end Alembic commands ###
