"""Adding new models to the db

Revision ID: 57cb73c443ff
Revises: 668364ea5a8c
Create Date: 2021-02-06 19:47:00.022285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "57cb73c443ff"
down_revision = "668364ea5a8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_model", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_device_model"), "device", ["device_model"], unique=False
    )
    op.create_index(op.f("ix_device_id"), "device", ["id"], unique=False)
    op.create_table(
        "site",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("public_private", sa.String(), nullable=True),
        sa.Column("masked_coord", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_site_id"), "site", ["id"], unique=False)
    op.create_index(op.f("ix_site_latitude"), "site", ["latitude"], unique=False)
    op.create_index(op.f("ix_site_longitude"), "site", ["longitude"], unique=False)
    op.create_index(
        op.f("ix_site_masked_coord"), "site", ["masked_coord"], unique=False
    )
    op.create_index(op.f("ix_site_name"), "site", ["name"], unique=False)
    op.create_index(
        op.f("ix_site_public_private"), "site", ["public_private"], unique=False
    )
    op.create_index(op.f("ix_site_user_id"), "site", ["user_id"], unique=False)
    op.create_table(
        "media_label",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("begin_time", sa.Float(), nullable=True),
        sa.Column("end_time", sa.Float(), nullable=True),
        sa.Column("low_freq", sa.Float(), nullable=True),
        sa.Column("high_freq", sa.Float(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("label_type", sa.String(), nullable=True),
        sa.Column("label_confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_media_label_begin_time"), "media_label", ["begin_time"], unique=False
    )
    op.create_index(
        op.f("ix_media_label_end_time"), "media_label", ["end_time"], unique=False
    )
    op.create_index(
        op.f("ix_media_label_high_freq"), "media_label", ["high_freq"], unique=False
    )
    op.create_index(op.f("ix_media_label_id"), "media_label", ["id"], unique=False)
    op.create_index(
        op.f("ix_media_label_label"), "media_label", ["label"], unique=False
    )
    op.create_index(
        op.f("ix_media_label_label_confidence"),
        "media_label",
        ["label_confidence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_label_label_type"), "media_label", ["label_type"], unique=False
    )
    op.create_index(
        op.f("ix_media_label_low_freq"), "media_label", ["low_freq"], unique=False
    )
    op.create_index(
        op.f("ix_media_label_media_id"), "media_label", ["media_id"], unique=False
    )
    op.add_column("media", sa.Column("device_id", sa.Integer(), nullable=True))
    op.alter_column(
        "media",
        "type",
        existing_type=postgresql.ENUM("undefined", "sound", "image", name="media_type"),
        type_=sa.Enum("undefined", "sound", "image", name="media_type"),
        existing_nullable=False,
        existing_server_default=sa.text("'sound'::media_type"),
    )
    op.create_index(op.f("ix_media_device_id"), "media", ["device_id"], unique=False)
    op.create_foreign_key("fk_media_device", "media", "device", ["device_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_media_device", "media", type_="foreignkey")
    op.drop_index(op.f("ix_media_device_id"), table_name="media")
    op.alter_column(
        "media",
        "type",
        existing_type=sa.Enum("undefined", "sound", "image", name="media_type"),
        type_=postgresql.ENUM("undefined", "sound", "image", name="media_type"),
        existing_nullable=False,
        existing_server_default=sa.text("'sound'::media_type"),
    )
    op.drop_column("media", "device_id")
    op.drop_index(op.f("ix_media_label_media_id"), table_name="media_label")
    op.drop_index(op.f("ix_media_label_low_freq"), table_name="media_label")
    op.drop_index(op.f("ix_media_label_label_type"), table_name="media_label")
    op.drop_index(op.f("ix_media_label_label_confidence"), table_name="media_label")
    op.drop_index(op.f("ix_media_label_label"), table_name="media_label")
    op.drop_index(op.f("ix_media_label_id"), table_name="media_label")
    op.drop_index(op.f("ix_media_label_high_freq"), table_name="media_label")
    op.drop_index(op.f("ix_media_label_end_time"), table_name="media_label")
    op.drop_index(op.f("ix_media_label_begin_time"), table_name="media_label")
    op.drop_table("media_label")
    op.drop_index(op.f("ix_site_user_id"), table_name="site")
    op.drop_index(op.f("ix_site_public_private"), table_name="site")
    op.drop_index(op.f("ix_site_name"), table_name="site")
    op.drop_index(op.f("ix_site_masked_coord"), table_name="site")
    op.drop_index(op.f("ix_site_longitude"), table_name="site")
    op.drop_index(op.f("ix_site_latitude"), table_name="site")
    op.drop_index(op.f("ix_site_id"), table_name="site")
    op.drop_table("site")
    op.drop_index(op.f("ix_device_id"), table_name="device")
    op.drop_index(op.f("ix_device_device_model"), table_name="device")
    op.drop_table("device")
    # ### end Alembic commands ###
