"""Add standardlabel and species models

Revision ID: 606355d946a8
Revises: 3f45586f3bd5
Create Date: 2021-03-07 23:20:29.553594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '606355d946a8'
down_revision = '3db3fb6ebadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_bird', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_name'), 'species', ['name'], unique=False)
    op.create_table('standardlabel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standardlabel_name'), 'standardlabel', ['name'], unique=False)
    op.drop_index('ix_device_id', table_name='device')

    op.drop_index('ix_media_created_by', table_name='media')
    op.drop_index('ix_media_device_id', table_name='media')
    op.drop_index('ix_media_id', table_name='media')
    op.drop_index('ix_media_origin_id', table_name='media')
    op.drop_index('ix_media_site_id', table_name='media')
    op.drop_index('ix_media_updated_by', table_name='media')
    op.add_column('medialabel', sa.Column('label_id', sa.Integer(), nullable=True))
    op.drop_index('ix_medialabel_begin_time', table_name='medialabel')
    op.drop_index('ix_medialabel_created_by', table_name='medialabel')
    op.drop_index('ix_medialabel_end_time', table_name='medialabel')
    op.drop_index('ix_medialabel_high_freq', table_name='medialabel')
    op.drop_index('ix_medialabel_id', table_name='medialabel')
    op.drop_index('ix_medialabel_label', table_name='medialabel')
    op.drop_index('ix_medialabel_label_type', table_name='medialabel')
    op.drop_index('ix_medialabel_low_freq', table_name='medialabel')
    op.drop_index('ix_medialabel_media_id', table_name='medialabel')
    op.drop_index('ix_medialabel_updated_by', table_name='medialabel')
    op.create_foreign_key('fk_medialabel_label_id', 'medialabel', 'standardlabel', ['label_id'], ['id'])
    op.drop_column('medialabel', 'label')
    op.drop_column('medialabel', 'label_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medialabel', sa.Column('label_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('medialabel', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_medialabel_label_id', 'medialabel', type_='foreignkey')
    op.create_index('ix_medialabel_updated_by', 'medialabel', ['updated_by'], unique=False)
    op.create_index('ix_medialabel_media_id', 'medialabel', ['media_id'], unique=False)
    op.create_index('ix_medialabel_low_freq', 'medialabel', ['low_freq'], unique=False)
    op.create_index('ix_medialabel_label_type', 'medialabel', ['label_type'], unique=False)
    op.create_index('ix_medialabel_label', 'medialabel', ['label'], unique=False)
    op.create_index('ix_medialabel_id', 'medialabel', ['id'], unique=False)
    op.create_index('ix_medialabel_high_freq', 'medialabel', ['high_freq'], unique=False)
    op.create_index('ix_medialabel_end_time', 'medialabel', ['end_time'], unique=False)
    op.create_index('ix_medialabel_created_by', 'medialabel', ['created_by'], unique=False)
    op.create_index('ix_medialabel_begin_time', 'medialabel', ['begin_time'], unique=False)
    op.drop_column('medialabel', 'label_id')
    op.create_index('ix_media_updated_by', 'media', ['updated_by'], unique=False)
    op.create_index('ix_media_site_id', 'media', ['site_id'], unique=False)
    op.create_index('ix_media_origin_id', 'media', ['origin_id'], unique=False)
    op.create_index('ix_media_id', 'media', ['id'], unique=False)
    op.create_index('ix_media_device_id', 'media', ['device_id'], unique=False)
    op.create_index('ix_media_created_by', 'media', ['created_by'], unique=False)
    op.create_index('ix_device_id', 'device', ['id'], unique=False)
    op.drop_index(op.f('ix_standardlabel_name'), table_name='standardlabel')
    op.drop_table('standardlabel')
    op.drop_index(op.f('ix_species_name'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###
