"""Add Media Table

Revision ID: 668364ea5a8c
Revises: d4867f3a4c0a
Create Date: 2021-01-31 08:30:40.653375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '668364ea5a8c'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('undefined', 'sound', 'image', name='media_type'), nullable=False,  default="sound", server_default="sound"),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_source', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_file_source'), 'media', ['file_source'], unique=False)
    op.create_index(op.f('ix_media_file_url'), 'media', ['file_url'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_media_owner_id'), 'media', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_origin_id'), 'media', ['origin_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_origin_id'), table_name='media')
    op.drop_index(op.f('ix_media_owner_id'), table_name='media')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_media_file_url'), table_name='media')
    op.drop_index(op.f('ix_media_file_source'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
