"""Add unique constraint on medialabel to avoid double annotations

Revision ID: 7dc4ec93ecee
Revises: 606355d946a8
Create Date: 2021-03-11 16:40:22.401969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7dc4ec93ecee'
down_revision = '606355d946a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_medialabel', 'medialabel', ['begin_time', 'media_id', 'label_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_medialabel', 'medialabel', type_='unique')
    # ### end Alembic commands ###
