"""Add column code to Species model

Revision ID: a9db58bd03dc
Revises: ccc3ff2274d0
Create Date: 2021-04-23 18:08:51.850015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9db58bd03dc'
down_revision = 'ccc3ff2274d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('code', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_species_code'), 'species', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_species_code'), table_name='species')
    op.drop_column('species', 'code')
    # ### end Alembic commands ###
