"""adding precision column for site model

Revision ID: c66154026535
Revises: 57cb73c443ff
Create Date: 2021-02-25 19:24:58.596863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c66154026535'
down_revision = '57cb73c443ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('locality_precision', sa.Float(), nullable=True))
    op.create_index(op.f('ix_site_locality_precision'), 'site', ['locality_precision'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_locality_precision'), table_name='site')
    op.drop_column('site', 'locality_precision')
    # ### end Alembic commands ###
