FROM node:alpine

# Create app directory
RUN mkdir -p /usr/app
WORKDIR /usr/app

# Installing dependencies
COPY package*.json /
RUN npm install

COPY . /

RUN npm run build

EXPOSE 3000

# Running the app
CMD "npm" "run" "dev"
